stages:
  - mirror

mirror:
  tags: 
    - shell
  stage: mirror
  variables:
    TARGET_REPO: "git@github.com:Citeck/ecos-webapp-sample.git"
    GIT_STRATEGY: clone
  cache: {}
  only:
    - main
  script:
    - mkdir -p ~/.ssh                                              
    - echo $GITHUB_MIRROR_PRIVATE | base64 -d > ~/.ssh/id_rsa      
    - echo $GITHUB_MIRROR_PUBLIC > ~/.ssh/id_rsa.pub               
    - ssh-keyscan -t rsa,dsa,ecdsa github.com >> ~/.ssh/known_hosts
    - chmod -R go-rwx ~/.ssh
    - git remote add mirror $TARGET_REPO
    - git remote show mirror
    - git fetch --unshallow origin
    - git checkout main
    - git push -f --progress mirror HEAD:main