# ===================================================================
# Application specific properties
# Add your own application properties here,
# ===================================================================

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/sample
    username: sample
    password:

server:
  port: 8077
